with-expecter: true
issue-845-fix: true
mockname: "{{.InterfaceName}}"
outpkg: mocks
packages:
  github.com/rshelekhov/sso/internal/domain/service/clientvalidator:
    config:
      dir: internal/domain/service/clientvalidator/mocks
    interfaces:
      Storage:
  github.com/rshelekhov/sso/internal/domain/service/session:
    config:
      dir: internal/domain/service/session/mocks
    interfaces:
      JWTManager:
      SessionStorage:
      DeviceStorage:
  github.com/rshelekhov/sso/internal/domain/service/token:
    config:
      dir: internal/domain/service/token/mocks
    interfaces:
      KeyStorage:
  github.com/rshelekhov/sso/internal/domain/service/userdata:
    config:
      dir: internal/domain/service/userdata/mocks
    interfaces:
      Storage:
  github.com/rshelekhov/sso/internal/domain/service/verification:
    config:
      dir: internal/domain/service/verification/mocks
    interfaces:
      Storage:
  github.com/rshelekhov/sso/internal/domain/usecase/client:
    config:
      dir: internal/domain/usecase/client/mocks
    interfaces:
      KeyManager:
      Storage:
  github.com/rshelekhov/sso/internal/domain/usecase/auth:
    config:
      dir: internal/domain/usecase/auth/mocks
    interfaces:
      SessionManager:
      UserdataManager:
      MailService:
      TokenManager:
      VerificationManager:
      TransactionManager:
      Storage:
  github.com/rshelekhov/sso/internal/domain/usecase/user:
    config:
      dir: internal/domain/usecase/user/mocks
    interfaces:
      ContextManager:
      AppValidator:
      RBACManager:
      SessionManager:
      UserdataManager:
      PasswordManager:
      IdentityManager:
      VerificationManager:
      TransactionManager:
      MetricsRecorder:
