// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error
	DeleteAllSessions(ctx context.Context, arg DeleteAllSessionsParams) error
	DeleteRefreshTokenFromSession(ctx context.Context, refreshToken string) error
	DeleteSession(ctx context.Context, arg DeleteSessionParams) error
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (GetSessionByRefreshTokenRow, error)
	GetUserDeviceID(ctx context.Context, arg GetUserDeviceIDParams) (string, error)
	RegisterDevice(ctx context.Context, arg RegisterDeviceParams) error
	UpdateLastVisitedAt(ctx context.Context, arg UpdateLastVisitedAtParams) error
}

var _ Querier = (*Queries)(nil)
