// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// CheckClientIDExists provides a mock function with given fields: ctx, clientID
func (_m *Storage) CheckClientIDExists(ctx context.Context, clientID string) error {
	ret := _m.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for CheckClientIDExists")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, clientID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_CheckClientIDExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckClientIDExists'
type Storage_CheckClientIDExists_Call struct {
	*mock.Call
}

// CheckClientIDExists is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *Storage_Expecter) CheckClientIDExists(ctx interface{}, clientID interface{}) *Storage_CheckClientIDExists_Call {
	return &Storage_CheckClientIDExists_Call{Call: _e.mock.On("CheckClientIDExists", ctx, clientID)}
}

func (_c *Storage_CheckClientIDExists_Call) Run(run func(ctx context.Context, clientID string)) *Storage_CheckClientIDExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_CheckClientIDExists_Call) Return(_a0 error) *Storage_CheckClientIDExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_CheckClientIDExists_Call) RunAndReturn(run func(context.Context, string) error) *Storage_CheckClientIDExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
