// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	CheckClientIDExists(ctx context.Context, id string) (bool, error)
	DeleteClient(ctx context.Context, arg DeleteClientParams) error
	InsertClient(ctx context.Context, arg InsertClientParams) error
}

var _ Querier = (*Queries)(nil)
