DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS token_types CASCADE;
DROP TABLE IF EXISTS tokens CASCADE;
DROP TABLE IF EXISTS apps CASCADE;
DROP TABLE IF EXISTS app_statuses CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS user_devices CASCADE;