DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS token_types CASCADE;
DROP TABLE IF EXISTS tokens CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS client_statuses CASCADE;
DROP TABLE IF EXISTS user_devices CASCADE;