// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// VerificationManager is an autogenerated mock type for the VerificationManager type
type VerificationManager struct {
	mock.Mock
}

type VerificationManager_Expecter struct {
	mock *mock.Mock
}

func (_m *VerificationManager) EXPECT() *VerificationManager_Expecter {
	return &VerificationManager_Expecter{mock: &_m.Mock}
}

// DeleteAllTokens provides a mock function with given fields: ctx, appID, userID
func (_m *VerificationManager) DeleteAllTokens(ctx context.Context, appID string, userID string) error {
	ret := _m.Called(ctx, appID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, appID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerificationManager_DeleteAllTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllTokens'
type VerificationManager_DeleteAllTokens_Call struct {
	*mock.Call
}

// DeleteAllTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - userID string
func (_e *VerificationManager_Expecter) DeleteAllTokens(ctx interface{}, appID interface{}, userID interface{}) *VerificationManager_DeleteAllTokens_Call {
	return &VerificationManager_DeleteAllTokens_Call{Call: _e.mock.On("DeleteAllTokens", ctx, appID, userID)}
}

func (_c *VerificationManager_DeleteAllTokens_Call) Run(run func(ctx context.Context, appID string, userID string)) *VerificationManager_DeleteAllTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *VerificationManager_DeleteAllTokens_Call) Return(_a0 error) *VerificationManager_DeleteAllTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VerificationManager_DeleteAllTokens_Call) RunAndReturn(run func(context.Context, string, string) error) *VerificationManager_DeleteAllTokens_Call {
	_c.Call.Return(run)
	return _c
}

// NewVerificationManager creates a new instance of VerificationManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerificationManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *VerificationManager {
	mock := &VerificationManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
