// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ClientValidator is an autogenerated mock type for the ClientValidator type
type ClientValidator struct {
	mock.Mock
}

type ClientValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientValidator) EXPECT() *ClientValidator_Expecter {
	return &ClientValidator_Expecter{mock: &_m.Mock}
}

// ValidateClientID provides a mock function with given fields: ctx, clientID
func (_m *ClientValidator) ValidateClientID(ctx context.Context, clientID string) error {
	ret := _m.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateClientID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, clientID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientValidator_ValidateClientID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateClientID'
type ClientValidator_ValidateClientID_Call struct {
	*mock.Call
}

// ValidateClientID is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *ClientValidator_Expecter) ValidateClientID(ctx interface{}, clientID interface{}) *ClientValidator_ValidateClientID_Call {
	return &ClientValidator_ValidateClientID_Call{Call: _e.mock.On("ValidateClientID", ctx, clientID)}
}

func (_c *ClientValidator_ValidateClientID_Call) Run(run func(ctx context.Context, clientID string)) *ClientValidator_ValidateClientID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClientValidator_ValidateClientID_Call) Return(_a0 error) *ClientValidator_ValidateClientID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClientValidator_ValidateClientID_Call) RunAndReturn(run func(context.Context, string) error) *ClientValidator_ValidateClientID_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientValidator creates a new instance of ClientValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientValidator {
	mock := &ClientValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
