// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PasswordManager is an autogenerated mock type for the PasswordManager type
type PasswordManager struct {
	mock.Mock
}

type PasswordManager_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordManager) EXPECT() *PasswordManager_Expecter {
	return &PasswordManager_Expecter{mock: &_m.Mock}
}

// HashPassword provides a mock function with given fields: password
func (_m *PasswordManager) HashPassword(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PasswordManager_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type PasswordManager_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password string
func (_e *PasswordManager_Expecter) HashPassword(password interface{}) *PasswordManager_HashPassword_Call {
	return &PasswordManager_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *PasswordManager_HashPassword_Call) Run(run func(password string)) *PasswordManager_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PasswordManager_HashPassword_Call) Return(_a0 string, _a1 error) *PasswordManager_HashPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PasswordManager_HashPassword_Call) RunAndReturn(run func(string) (string, error)) *PasswordManager_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

// PasswordMatch provides a mock function with given fields: hash, password
func (_m *PasswordManager) PasswordMatch(hash string, password string) (bool, error) {
	ret := _m.Called(hash, password)

	if len(ret) == 0 {
		panic("no return value specified for PasswordMatch")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(hash, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(hash, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(hash, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PasswordManager_PasswordMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasswordMatch'
type PasswordManager_PasswordMatch_Call struct {
	*mock.Call
}

// PasswordMatch is a helper method to define mock.On call
//   - hash string
//   - password string
func (_e *PasswordManager_Expecter) PasswordMatch(hash interface{}, password interface{}) *PasswordManager_PasswordMatch_Call {
	return &PasswordManager_PasswordMatch_Call{Call: _e.mock.On("PasswordMatch", hash, password)}
}

func (_c *PasswordManager_PasswordMatch_Call) Run(run func(hash string, password string)) *PasswordManager_PasswordMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *PasswordManager_PasswordMatch_Call) Return(_a0 bool, _a1 error) *PasswordManager_PasswordMatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PasswordManager_PasswordMatch_Call) RunAndReturn(run func(string, string) (bool, error)) *PasswordManager_PasswordMatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewPasswordManager creates a new instance of PasswordManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordManager {
	mock := &PasswordManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
