// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	rbac "github.com/rshelekhov/sso/internal/domain/service/rbac"
	mock "github.com/stretchr/testify/mock"
)

// RBACManager is an autogenerated mock type for the RBACManager type
type RBACManager struct {
	mock.Mock
}

type RBACManager_Expecter struct {
	mock *mock.Mock
}

func (_m *RBACManager) EXPECT() *RBACManager_Expecter {
	return &RBACManager_Expecter{mock: &_m.Mock}
}

// GetUserRole provides a mock function with given fields: ctx, appID, userID
func (_m *RBACManager) GetUserRole(ctx context.Context, appID string, userID string) (rbac.Role, error) {
	ret := _m.Called(ctx, appID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRole")
	}

	var r0 rbac.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (rbac.Role, error)); ok {
		return rf(ctx, appID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) rbac.Role); ok {
		r0 = rf(ctx, appID, userID)
	} else {
		r0 = ret.Get(0).(rbac.Role)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, appID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RBACManager_GetUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRole'
type RBACManager_GetUserRole_Call struct {
	*mock.Call
}

// GetUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - userID string
func (_e *RBACManager_Expecter) GetUserRole(ctx interface{}, appID interface{}, userID interface{}) *RBACManager_GetUserRole_Call {
	return &RBACManager_GetUserRole_Call{Call: _e.mock.On("GetUserRole", ctx, appID, userID)}
}

func (_c *RBACManager_GetUserRole_Call) Run(run func(ctx context.Context, appID string, userID string)) *RBACManager_GetUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *RBACManager_GetUserRole_Call) Return(_a0 rbac.Role, _a1 error) *RBACManager_GetUserRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RBACManager_GetUserRole_Call) RunAndReturn(run func(context.Context, string, string) (rbac.Role, error)) *RBACManager_GetUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserRole provides a mock function with given fields: ctx, appID, userID, role
func (_m *RBACManager) SetUserRole(ctx context.Context, appID string, userID string, role rbac.Role) error {
	ret := _m.Called(ctx, appID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for SetUserRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, rbac.Role) error); ok {
		r0 = rf(ctx, appID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RBACManager_SetUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserRole'
type RBACManager_SetUserRole_Call struct {
	*mock.Call
}

// SetUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - userID string
//   - role rbac.Role
func (_e *RBACManager_Expecter) SetUserRole(ctx interface{}, appID interface{}, userID interface{}, role interface{}) *RBACManager_SetUserRole_Call {
	return &RBACManager_SetUserRole_Call{Call: _e.mock.On("SetUserRole", ctx, appID, userID, role)}
}

func (_c *RBACManager_SetUserRole_Call) Run(run func(ctx context.Context, appID string, userID string, role rbac.Role)) *RBACManager_SetUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(rbac.Role))
	})
	return _c
}

func (_c *RBACManager_SetUserRole_Call) Return(_a0 error) *RBACManager_SetUserRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RBACManager_SetUserRole_Call) RunAndReturn(run func(context.Context, string, string, rbac.Role) error) *RBACManager_SetUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewRBACManager creates a new instance of RBACManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRBACManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *RBACManager {
	mock := &RBACManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
