// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	attribute "go.opentelemetry.io/otel/attribute"

	mock "github.com/stretchr/testify/mock"
)

// MetricsRecorder is an autogenerated mock type for the MetricsRecorder type
type MetricsRecorder struct {
	mock.Mock
}

type MetricsRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MetricsRecorder) EXPECT() *MetricsRecorder_Expecter {
	return &MetricsRecorder_Expecter{mock: &_m.Mock}
}

// RecordUserDeletionsAttempt provides a mock function with given fields: ctx, clientID
func (_m *MetricsRecorder) RecordUserDeletionsAttempt(ctx context.Context, clientID string) {
	_m.Called(ctx, clientID)
}

// MetricsRecorder_RecordUserDeletionsAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordUserDeletionsAttempt'
type MetricsRecorder_RecordUserDeletionsAttempt_Call struct {
	*mock.Call
}

// RecordUserDeletionsAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *MetricsRecorder_Expecter) RecordUserDeletionsAttempt(ctx interface{}, clientID interface{}) *MetricsRecorder_RecordUserDeletionsAttempt_Call {
	return &MetricsRecorder_RecordUserDeletionsAttempt_Call{Call: _e.mock.On("RecordUserDeletionsAttempt", ctx, clientID)}
}

func (_c *MetricsRecorder_RecordUserDeletionsAttempt_Call) Run(run func(ctx context.Context, clientID string)) *MetricsRecorder_RecordUserDeletionsAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MetricsRecorder_RecordUserDeletionsAttempt_Call) Return() *MetricsRecorder_RecordUserDeletionsAttempt_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsRecorder_RecordUserDeletionsAttempt_Call) RunAndReturn(run func(context.Context, string)) *MetricsRecorder_RecordUserDeletionsAttempt_Call {
	_c.Run(run)
	return _c
}

// RecordUserDeletionsError provides a mock function with given fields: ctx, clientID, attrs
func (_m *MetricsRecorder) RecordUserDeletionsError(ctx context.Context, clientID string, attrs ...attribute.KeyValue) {
	_va := make([]interface{}, len(attrs))
	for _i := range attrs {
		_va[_i] = attrs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, clientID)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MetricsRecorder_RecordUserDeletionsError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordUserDeletionsError'
type MetricsRecorder_RecordUserDeletionsError_Call struct {
	*mock.Call
}

// RecordUserDeletionsError is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - attrs ...attribute.KeyValue
func (_e *MetricsRecorder_Expecter) RecordUserDeletionsError(ctx interface{}, clientID interface{}, attrs ...interface{}) *MetricsRecorder_RecordUserDeletionsError_Call {
	return &MetricsRecorder_RecordUserDeletionsError_Call{Call: _e.mock.On("RecordUserDeletionsError",
		append([]interface{}{ctx, clientID}, attrs...)...)}
}

func (_c *MetricsRecorder_RecordUserDeletionsError_Call) Run(run func(ctx context.Context, clientID string, attrs ...attribute.KeyValue)) *MetricsRecorder_RecordUserDeletionsError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]attribute.KeyValue, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(attribute.KeyValue)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MetricsRecorder_RecordUserDeletionsError_Call) Return() *MetricsRecorder_RecordUserDeletionsError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsRecorder_RecordUserDeletionsError_Call) RunAndReturn(run func(context.Context, string, ...attribute.KeyValue)) *MetricsRecorder_RecordUserDeletionsError_Call {
	_c.Run(run)
	return _c
}

// RecordUserDeletionsSuccess provides a mock function with given fields: ctx, clientID
func (_m *MetricsRecorder) RecordUserDeletionsSuccess(ctx context.Context, clientID string) {
	_m.Called(ctx, clientID)
}

// MetricsRecorder_RecordUserDeletionsSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordUserDeletionsSuccess'
type MetricsRecorder_RecordUserDeletionsSuccess_Call struct {
	*mock.Call
}

// RecordUserDeletionsSuccess is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *MetricsRecorder_Expecter) RecordUserDeletionsSuccess(ctx interface{}, clientID interface{}) *MetricsRecorder_RecordUserDeletionsSuccess_Call {
	return &MetricsRecorder_RecordUserDeletionsSuccess_Call{Call: _e.mock.On("RecordUserDeletionsSuccess", ctx, clientID)}
}

func (_c *MetricsRecorder_RecordUserDeletionsSuccess_Call) Run(run func(ctx context.Context, clientID string)) *MetricsRecorder_RecordUserDeletionsSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MetricsRecorder_RecordUserDeletionsSuccess_Call) Return() *MetricsRecorder_RecordUserDeletionsSuccess_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsRecorder_RecordUserDeletionsSuccess_Call) RunAndReturn(run func(context.Context, string)) *MetricsRecorder_RecordUserDeletionsSuccess_Call {
	_c.Run(run)
	return _c
}

// RecordUserSearchRequest provides a mock function with given fields: ctx, clientID
func (_m *MetricsRecorder) RecordUserSearchRequest(ctx context.Context, clientID string) {
	_m.Called(ctx, clientID)
}

// MetricsRecorder_RecordUserSearchRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordUserSearchRequest'
type MetricsRecorder_RecordUserSearchRequest_Call struct {
	*mock.Call
}

// RecordUserSearchRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *MetricsRecorder_Expecter) RecordUserSearchRequest(ctx interface{}, clientID interface{}) *MetricsRecorder_RecordUserSearchRequest_Call {
	return &MetricsRecorder_RecordUserSearchRequest_Call{Call: _e.mock.On("RecordUserSearchRequest", ctx, clientID)}
}

func (_c *MetricsRecorder_RecordUserSearchRequest_Call) Run(run func(ctx context.Context, clientID string)) *MetricsRecorder_RecordUserSearchRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MetricsRecorder_RecordUserSearchRequest_Call) Return() *MetricsRecorder_RecordUserSearchRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsRecorder_RecordUserSearchRequest_Call) RunAndReturn(run func(context.Context, string)) *MetricsRecorder_RecordUserSearchRequest_Call {
	_c.Run(run)
	return _c
}

// RecordUserSearchResults provides a mock function with given fields: ctx, clientID, resultCount
func (_m *MetricsRecorder) RecordUserSearchResults(ctx context.Context, clientID string, resultCount int) {
	_m.Called(ctx, clientID, resultCount)
}

// MetricsRecorder_RecordUserSearchResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordUserSearchResults'
type MetricsRecorder_RecordUserSearchResults_Call struct {
	*mock.Call
}

// RecordUserSearchResults is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - resultCount int
func (_e *MetricsRecorder_Expecter) RecordUserSearchResults(ctx interface{}, clientID interface{}, resultCount interface{}) *MetricsRecorder_RecordUserSearchResults_Call {
	return &MetricsRecorder_RecordUserSearchResults_Call{Call: _e.mock.On("RecordUserSearchResults", ctx, clientID, resultCount)}
}

func (_c *MetricsRecorder_RecordUserSearchResults_Call) Run(run func(ctx context.Context, clientID string, resultCount int)) *MetricsRecorder_RecordUserSearchResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MetricsRecorder_RecordUserSearchResults_Call) Return() *MetricsRecorder_RecordUserSearchResults_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsRecorder_RecordUserSearchResults_Call) RunAndReturn(run func(context.Context, string, int)) *MetricsRecorder_RecordUserSearchResults_Call {
	_c.Run(run)
	return _c
}

// NewMetricsRecorder creates a new instance of MetricsRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsRecorder {
	mock := &MetricsRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
