// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/rshelekhov/sso/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// UserdataManager is an autogenerated mock type for the UserdataManager type
type UserdataManager struct {
	mock.Mock
}

type UserdataManager_Expecter struct {
	mock *mock.Mock
}

func (_m *UserdataManager) EXPECT() *UserdataManager_Expecter {
	return &UserdataManager_Expecter{mock: &_m.Mock}
}

// DeleteUser provides a mock function with given fields: ctx, _a1
func (_m *UserdataManager) DeleteUser(ctx context.Context, _a1 entity.User) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserdataManager_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type UserdataManager_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 entity.User
func (_e *UserdataManager_Expecter) DeleteUser(ctx interface{}, _a1 interface{}) *UserdataManager_DeleteUser_Call {
	return &UserdataManager_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, _a1)}
}

func (_c *UserdataManager_DeleteUser_Call) Run(run func(ctx context.Context, _a1 entity.User)) *UserdataManager_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.User))
	})
	return _c
}

func (_c *UserdataManager_DeleteUser_Call) Return(_a0 error) *UserdataManager_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserdataManager_DeleteUser_Call) RunAndReturn(run func(context.Context, entity.User) error) *UserdataManager_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, clientID, userID
func (_m *UserdataManager) GetUserByID(ctx context.Context, clientID string, userID string) (entity.User, error) {
	ret := _m.Called(ctx, clientID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (entity.User, error)); ok {
		return rf(ctx, clientID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) entity.User); ok {
		r0 = rf(ctx, clientID, userID)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, clientID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserdataManager_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type UserdataManager_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - userID string
func (_e *UserdataManager_Expecter) GetUserByID(ctx interface{}, clientID interface{}, userID interface{}) *UserdataManager_GetUserByID_Call {
	return &UserdataManager_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, clientID, userID)}
}

func (_c *UserdataManager_GetUserByID_Call) Run(run func(ctx context.Context, clientID string, userID string)) *UserdataManager_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserdataManager_GetUserByID_Call) Return(_a0 entity.User, _a1 error) *UserdataManager_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserdataManager_GetUserByID_Call) RunAndReturn(run func(context.Context, string, string) (entity.User, error)) *UserdataManager_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserData provides a mock function with given fields: ctx, clientID, userID
func (_m *UserdataManager) GetUserData(ctx context.Context, clientID string, userID string) (entity.User, error) {
	ret := _m.Called(ctx, clientID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserData")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (entity.User, error)); ok {
		return rf(ctx, clientID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) entity.User); ok {
		r0 = rf(ctx, clientID, userID)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, clientID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserdataManager_GetUserData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserData'
type UserdataManager_GetUserData_Call struct {
	*mock.Call
}

// GetUserData is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - userID string
func (_e *UserdataManager_Expecter) GetUserData(ctx interface{}, clientID interface{}, userID interface{}) *UserdataManager_GetUserData_Call {
	return &UserdataManager_GetUserData_Call{Call: _e.mock.On("GetUserData", ctx, clientID, userID)}
}

func (_c *UserdataManager_GetUserData_Call) Run(run func(ctx context.Context, clientID string, userID string)) *UserdataManager_GetUserData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserdataManager_GetUserData_Call) Return(_a0 entity.User, _a1 error) *UserdataManager_GetUserData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserdataManager_GetUserData_Call) RunAndReturn(run func(context.Context, string, string) (entity.User, error)) *UserdataManager_GetUserData_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserStatusByEmail provides a mock function with given fields: ctx, clientID, email
func (_m *UserdataManager) GetUserStatusByEmail(ctx context.Context, clientID string, email string) (string, error) {
	ret := _m.Called(ctx, clientID, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserStatusByEmail")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, clientID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, clientID, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, clientID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserdataManager_GetUserStatusByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserStatusByEmail'
type UserdataManager_GetUserStatusByEmail_Call struct {
	*mock.Call
}

// GetUserStatusByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - email string
func (_e *UserdataManager_Expecter) GetUserStatusByEmail(ctx interface{}, clientID interface{}, email interface{}) *UserdataManager_GetUserStatusByEmail_Call {
	return &UserdataManager_GetUserStatusByEmail_Call{Call: _e.mock.On("GetUserStatusByEmail", ctx, clientID, email)}
}

func (_c *UserdataManager_GetUserStatusByEmail_Call) Run(run func(ctx context.Context, clientID string, email string)) *UserdataManager_GetUserStatusByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserdataManager_GetUserStatusByEmail_Call) Return(_a0 string, _a1 error) *UserdataManager_GetUserStatusByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserdataManager_GetUserStatusByEmail_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *UserdataManager_GetUserStatusByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserStatusByID provides a mock function with given fields: ctx, clientID, userID
func (_m *UserdataManager) GetUserStatusByID(ctx context.Context, clientID string, userID string) (string, error) {
	ret := _m.Called(ctx, clientID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserStatusByID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, clientID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, clientID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, clientID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserdataManager_GetUserStatusByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserStatusByID'
type UserdataManager_GetUserStatusByID_Call struct {
	*mock.Call
}

// GetUserStatusByID is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - userID string
func (_e *UserdataManager_Expecter) GetUserStatusByID(ctx interface{}, clientID interface{}, userID interface{}) *UserdataManager_GetUserStatusByID_Call {
	return &UserdataManager_GetUserStatusByID_Call{Call: _e.mock.On("GetUserStatusByID", ctx, clientID, userID)}
}

func (_c *UserdataManager_GetUserStatusByID_Call) Run(run func(ctx context.Context, clientID string, userID string)) *UserdataManager_GetUserStatusByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserdataManager_GetUserStatusByID_Call) Return(_a0 string, _a1 error) *UserdataManager_GetUserStatusByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserdataManager_GetUserStatusByID_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *UserdataManager_GetUserStatusByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserData provides a mock function with given fields: ctx, _a1
func (_m *UserdataManager) UpdateUserData(ctx context.Context, _a1 entity.User) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserdataManager_UpdateUserData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserData'
type UserdataManager_UpdateUserData_Call struct {
	*mock.Call
}

// UpdateUserData is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 entity.User
func (_e *UserdataManager_Expecter) UpdateUserData(ctx interface{}, _a1 interface{}) *UserdataManager_UpdateUserData_Call {
	return &UserdataManager_UpdateUserData_Call{Call: _e.mock.On("UpdateUserData", ctx, _a1)}
}

func (_c *UserdataManager_UpdateUserData_Call) Run(run func(ctx context.Context, _a1 entity.User)) *UserdataManager_UpdateUserData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.User))
	})
	return _c
}

func (_c *UserdataManager_UpdateUserData_Call) Return(_a0 error) *UserdataManager_UpdateUserData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserdataManager_UpdateUserData_Call) RunAndReturn(run func(context.Context, entity.User) error) *UserdataManager_UpdateUserData_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserdataManager creates a new instance of UserdataManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserdataManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserdataManager {
	mock := &UserdataManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
