// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetUserDeviceID(ctx context.Context, arg GetUserDeviceIDParams) (string, error)
	RegisterDevice(ctx context.Context, arg RegisterDeviceParams) error
	UpdateLastVisitedAt(ctx context.Context, arg UpdateLastVisitedAtParams) error
}

var _ Querier = (*Queries)(nil)
