// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetUserRole(ctx context.Context, arg GetUserRoleParams) (string, error)
	SetUserRole(ctx context.Context, arg SetUserRoleParams) (string, error)
}

var _ Querier = (*Queries)(nil)
