// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	DeleteVerificationToken(ctx context.Context, token string) error
	GetVerificationTokenData(ctx context.Context, token string) (GetVerificationTokenDataRow, error)
	SaveVerificationToken(ctx context.Context, arg SaveVerificationTokenParams) error
}

var _ Querier = (*Queries)(nil)
