# Prometheus Configuration for SSO Application
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rules for alerts (optional)
rule_files:
  # - "alert_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # SSO application metrics (gRPC service - no HTTP metrics endpoint)
  # Metrics are collected via OTLP -> Tempo -> Prometheus integration
  # If you need direct Prometheus metrics, add HTTP server to SSO app
  # - job_name: "sso-app"
  #   static_configs:
  #     - targets: ["sso:8080"]
  #   metrics_path: /metrics
  #   scrape_interval: 5s

  # Grafana metrics
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    metrics_path: /metrics

  # Tempo metrics
  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
    metrics_path: /metrics

  # Loki metrics
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
    metrics_path: /metrics

  # Redis metrics (if Redis exporter is added)
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]

  # PostgreSQL metrics (if PostgreSQL exporter is added)
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]

  # MongoDB metrics (if MongoDB exporter is added)
  - job_name: "mongo"
    static_configs:
      - targets: ["mongo:27017"]

  # MinIO metrics (if MinIO exporter is added)
  - job_name: "minio"
    static_configs:
      - targets: ["minio:9000"]

  # OTEL Collector metrics (SSO app metrics via OTLP)
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
    metrics_path: /metrics
    scrape_interval: 5s

  # SSO application metrics (gRPC service - no HTTP metrics endpoint)
  # Metrics are collected via OTLP -> OTEL Collector -> Prometheus integration
  # If you need direct Prometheus metrics, add HTTP server to SSO app
  # - job_name: "sso-app"
  #   static_configs:
  #     - targets: ["sso:8080"]
  #   metrics_path: /metrics
  #   scrape_interval: 5s
