// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (GetUserByIDRow, error)
	GetUserData(ctx context.Context, arg GetUserDataParams) (GetUserDataRow, error)
	GetUserStatusByEmail(ctx context.Context, arg GetUserStatusByEmailParams) (string, error)
	GetUserStatusByID(ctx context.Context, arg GetUserStatusByIDParams) (string, error)
}

var _ Querier = (*Queries)(nil)
