// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSearchUsers = `-- name: CountSearchUsers :one
SELECT COUNT(*)
FROM users
WHERE deleted_at IS NULL
  AND (
    email ILIKE '%' || $1::text || '%'
    OR name ILIKE '%' || $1::text || '%'
  )
`

func (q *Queries) CountSearchUsers(ctx context.Context, query string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchUsers, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = $1
WHERE id = $2
  AND deleted_at IS NULL
`

type DeleteUserParams struct {
	DeletedAt pgtype.Timestamptz `db:"deleted_at"`
	ID        string             `db:"id"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.Exec(ctx, deleteUser, arg.DeletedAt, arg.ID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, updated_at
FROM users
WHERE email = $1
  AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID        string    `db:"id"`
	Email     string    `db:"email"`
	Name      string    `db:"name"`
	UpdatedAt time.Time `db:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name,verified, updated_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID        string      `db:"id"`
	Email     string      `db:"email"`
	Name      string      `db:"name"`
	Verified  pgtype.Bool `db:"verified"`
	UpdatedAt time.Time   `db:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Verified,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserData = `-- name: GetUserData :one
SELECT id, email, name, password_hash, updated_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserDataRow struct {
	ID           string    `db:"id"`
	Email        string    `db:"email"`
	Name         string    `db:"name"`
	PasswordHash string    `db:"password_hash"`
	UpdatedAt    time.Time `db:"updated_at"`
}

func (q *Queries) GetUserData(ctx context.Context, id string) (GetUserDataRow, error) {
	row := q.db.QueryRow(ctx, getUserData, id)
	var i GetUserDataRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserStatusByEmail = `-- name: GetUserStatusByEmail :one
SELECT CASE
           WHEN EXISTS(
               SELECT 1
               FROM users
               WHERE users.email = $1
                 AND deleted_at IS NULL
           ) THEN 'active'
           WHEN EXISTS(
               SELECT 1
               FROM users
               WHERE users.email = $1
                 AND deleted_at IS NOT NULL
           ) THEN 'soft_deleted'
           ELSE 'not_found' END AS status
`

func (q *Queries) GetUserStatusByEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRow(ctx, getUserStatusByEmail, email)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getUserStatusByID = `-- name: GetUserStatusByID :one
SELECT CASE
           WHEN EXISTS(
               SELECT 1
               FROM users
               WHERE users.id = $1
                 AND deleted_at IS NULL
           ) THEN 'active'
           WHEN EXISTS(
               SELECT 1
               FROM users
               WHERE users.id = $1
                 AND deleted_at IS NOT NULL
           ) THEN 'soft_deleted'
           ELSE 'not_found' END AS status
`

func (q *Queries) GetUserStatusByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getUserStatusByID, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, email, name, verified, created_at, updated_at
FROM users
WHERE deleted_at IS NULL
  AND (
    email ILIKE '%' || $1::text || '%'
    OR name ILIKE '%' || $1::text || '%'
  )
  AND (
    -- Cursor filtering: return results BEFORE the cursor (created_at < cursor OR (created_at = cursor AND id < cursor_id))
    $2::timestamptz IS NULL
    OR created_at < $2::timestamptz
    OR (created_at = $2::timestamptz
        AND id < $3::text)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type SearchUsersParams struct {
	Query           string             `db:"query"`
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at"`
	CursorID        pgtype.Text        `db:"cursor_id"`
	PageSize        int32              `db:"page_size"`
}

type SearchUsersRow struct {
	ID        string      `db:"id"`
	Email     string      `db:"email"`
	Name      string      `db:"name"`
	Verified  pgtype.Bool `db:"verified"`
	CreatedAt time.Time   `db:"created_at"`
	UpdatedAt time.Time   `db:"updated_at"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers,
		arg.Query,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
