# General test data
test_issuer: sso
test_client_id: test-client-id
test_verification_url: reframedapp.com/verify-email/token=
test_confirm_change_password_url: reframedapp.com/password/change?token=
