# Test configuration for API tests against Docker Compose
test_issuer: "sso"
test_client_id: "test-client-id"
test_verification_url: "http://localhost:44044"
test_confirm_change_password_url: "http://localhost:44044"
