// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	MarkEmailVerified(ctx context.Context, id string) error
	RegisterUser(ctx context.Context, arg RegisterUserParams) error
	ReplaceSoftDeletedUser(ctx context.Context, arg ReplaceSoftDeletedUserParams) error
}

var _ Querier = (*Queries)(nil)
