// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/rshelekhov/sso/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// CountSearchUsers provides a mock function with given fields: ctx, query
func (_m *Storage) CountSearchUsers(ctx context.Context, query string) (int32, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for CountSearchUsers")
	}

	var r0 int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int32, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int32); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(int32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_CountSearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSearchUsers'
type Storage_CountSearchUsers_Call struct {
	*mock.Call
}

// CountSearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *Storage_Expecter) CountSearchUsers(ctx interface{}, query interface{}) *Storage_CountSearchUsers_Call {
	return &Storage_CountSearchUsers_Call{Call: _e.mock.On("CountSearchUsers", ctx, query)}
}

func (_c *Storage_CountSearchUsers_Call) Run(run func(ctx context.Context, query string)) *Storage_CountSearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_CountSearchUsers_Call) Return(_a0 int32, _a1 error) *Storage_CountSearchUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_CountSearchUsers_Call) RunAndReturn(run func(context.Context, string) (int32, error)) *Storage_CountSearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, user
func (_m *Storage) DeleteUser(ctx context.Context, user entity.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type Storage_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user entity.User
func (_e *Storage_Expecter) DeleteUser(ctx interface{}, user interface{}) *Storage_DeleteUser_Call {
	return &Storage_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, user)}
}

func (_c *Storage_DeleteUser_Call) Run(run func(ctx context.Context, user entity.User)) *Storage_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.User))
	})
	return _c
}

func (_c *Storage_DeleteUser_Call) Return(_a0 error) *Storage_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_DeleteUser_Call) RunAndReturn(run func(context.Context, entity.User) error) *Storage_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *Storage) GetUserByEmail(ctx context.Context, email string) (entity.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type Storage_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *Storage_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *Storage_GetUserByEmail_Call {
	return &Storage_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *Storage_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *Storage_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_GetUserByEmail_Call) Return(_a0 entity.User, _a1 error) *Storage_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (entity.User, error)) *Storage_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *Storage) GetUserByID(ctx context.Context, userID string) (entity.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.User); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type Storage_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Storage_Expecter) GetUserByID(ctx interface{}, userID interface{}) *Storage_GetUserByID_Call {
	return &Storage_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *Storage_GetUserByID_Call) Run(run func(ctx context.Context, userID string)) *Storage_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_GetUserByID_Call) Return(_a0 entity.User, _a1 error) *Storage_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetUserByID_Call) RunAndReturn(run func(context.Context, string) (entity.User, error)) *Storage_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserData provides a mock function with given fields: ctx, userID
func (_m *Storage) GetUserData(ctx context.Context, userID string) (entity.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserData")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.User); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetUserData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserData'
type Storage_GetUserData_Call struct {
	*mock.Call
}

// GetUserData is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Storage_Expecter) GetUserData(ctx interface{}, userID interface{}) *Storage_GetUserData_Call {
	return &Storage_GetUserData_Call{Call: _e.mock.On("GetUserData", ctx, userID)}
}

func (_c *Storage_GetUserData_Call) Run(run func(ctx context.Context, userID string)) *Storage_GetUserData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_GetUserData_Call) Return(_a0 entity.User, _a1 error) *Storage_GetUserData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetUserData_Call) RunAndReturn(run func(context.Context, string) (entity.User, error)) *Storage_GetUserData_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserStatusByEmail provides a mock function with given fields: ctx, email
func (_m *Storage) GetUserStatusByEmail(ctx context.Context, email string) (string, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserStatusByEmail")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetUserStatusByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserStatusByEmail'
type Storage_GetUserStatusByEmail_Call struct {
	*mock.Call
}

// GetUserStatusByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *Storage_Expecter) GetUserStatusByEmail(ctx interface{}, email interface{}) *Storage_GetUserStatusByEmail_Call {
	return &Storage_GetUserStatusByEmail_Call{Call: _e.mock.On("GetUserStatusByEmail", ctx, email)}
}

func (_c *Storage_GetUserStatusByEmail_Call) Run(run func(ctx context.Context, email string)) *Storage_GetUserStatusByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_GetUserStatusByEmail_Call) Return(_a0 string, _a1 error) *Storage_GetUserStatusByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetUserStatusByEmail_Call) RunAndReturn(run func(context.Context, string) (string, error)) *Storage_GetUserStatusByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserStatusByID provides a mock function with given fields: ctx, userID
func (_m *Storage) GetUserStatusByID(ctx context.Context, userID string) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserStatusByID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetUserStatusByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserStatusByID'
type Storage_GetUserStatusByID_Call struct {
	*mock.Call
}

// GetUserStatusByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Storage_Expecter) GetUserStatusByID(ctx interface{}, userID interface{}) *Storage_GetUserStatusByID_Call {
	return &Storage_GetUserStatusByID_Call{Call: _e.mock.On("GetUserStatusByID", ctx, userID)}
}

func (_c *Storage_GetUserStatusByID_Call) Run(run func(ctx context.Context, userID string)) *Storage_GetUserStatusByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_GetUserStatusByID_Call) Return(_a0 string, _a1 error) *Storage_GetUserStatusByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetUserStatusByID_Call) RunAndReturn(run func(context.Context, string) (string, error)) *Storage_GetUserStatusByID_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function with given fields: ctx, query, limit, cursorCreatedAt, cursorID
func (_m *Storage) SearchUsers(ctx context.Context, query string, limit int32, cursorCreatedAt *time.Time, cursorID *string) ([]entity.User, error) {
	ret := _m.Called(ctx, query, limit, cursorCreatedAt, cursorID)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, *time.Time, *string) ([]entity.User, error)); ok {
		return rf(ctx, query, limit, cursorCreatedAt, cursorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, *time.Time, *string) []entity.User); ok {
		r0 = rf(ctx, query, limit, cursorCreatedAt, cursorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32, *time.Time, *string) error); ok {
		r1 = rf(ctx, query, limit, cursorCreatedAt, cursorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type Storage_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - limit int32
//   - cursorCreatedAt *time.Time
//   - cursorID *string
func (_e *Storage_Expecter) SearchUsers(ctx interface{}, query interface{}, limit interface{}, cursorCreatedAt interface{}, cursorID interface{}) *Storage_SearchUsers_Call {
	return &Storage_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, query, limit, cursorCreatedAt, cursorID)}
}

func (_c *Storage_SearchUsers_Call) Run(run func(ctx context.Context, query string, limit int32, cursorCreatedAt *time.Time, cursorID *string)) *Storage_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int32), args[3].(*time.Time), args[4].(*string))
	})
	return _c
}

func (_c *Storage_SearchUsers_Call) Return(_a0 []entity.User, _a1 error) *Storage_SearchUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_SearchUsers_Call) RunAndReturn(run func(context.Context, string, int32, *time.Time, *string) ([]entity.User, error)) *Storage_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, user
func (_m *Storage) UpdateUser(ctx context.Context, user entity.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type Storage_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user entity.User
func (_e *Storage_Expecter) UpdateUser(ctx interface{}, user interface{}) *Storage_UpdateUser_Call {
	return &Storage_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, user)}
}

func (_c *Storage_UpdateUser_Call) Run(run func(ctx context.Context, user entity.User)) *Storage_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.User))
	})
	return _c
}

func (_c *Storage_UpdateUser_Call) Return(_a0 error) *Storage_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_UpdateUser_Call) RunAndReturn(run func(context.Context, entity.User) error) *Storage_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
