// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: app.sql

package sqlc

import (
	"context"
	"time"
)

const insertApp = `-- name: InsertApp :exec
INSERT INTO apps (id, name, secret, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAppParams struct {
	ID        string    `db:"id"`
	Name      string    `db:"name"`
	Secret    string    `db:"secret"`
	Status    int32     `db:"status"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

func (q *Queries) InsertApp(ctx context.Context, arg InsertAppParams) error {
	_, err := q.db.Exec(ctx, insertApp,
		arg.ID,
		arg.Name,
		arg.Secret,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
