// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (GetSessionByRefreshTokenRow, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (GetUserByIDRow, error)
	GetUserData(ctx context.Context, arg GetUserDataParams) (GetUserDataRow, error)
	GetUserDeviceID(ctx context.Context, arg GetUserDeviceIDParams) (string, error)
	GetUserStatus(ctx context.Context, email string) (string, error)
	InsertUser(ctx context.Context, arg InsertUserParams) error
	RegisterDevice(ctx context.Context, arg RegisterDeviceParams) error
	SetDeletedUserAtNull(ctx context.Context, email string) error
	UpdateLatestLoginAt(ctx context.Context, arg UpdateLatestLoginAtParams) error
}

var _ Querier = (*Queries)(nil)
