// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetUserStatus(ctx context.Context, email string) (string, error)
	InsertUser(ctx context.Context, arg InsertUserParams) error
	SetDeletedUserAtNull(ctx context.Context, email string) error
}

var _ Querier = (*Queries)(nil)
