// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	CheckAppIDExists(ctx context.Context, id string) (bool, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) error
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error
	DeleteAllSessions(ctx context.Context, arg DeleteAllSessionsParams) error
	DeleteAllTokens(ctx context.Context, arg DeleteAllTokensParams) error
	DeleteApp(ctx context.Context, arg DeleteAppParams) error
	DeleteRefreshTokenFromSession(ctx context.Context, refreshToken string) error
	DeleteSession(ctx context.Context, arg DeleteSessionParams) error
	DeleteToken(ctx context.Context, token string) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (GetSessionByRefreshTokenRow, error)
	GetTokenData(ctx context.Context, token string) (GetTokenDataRow, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (GetUserByIDRow, error)
	GetUserData(ctx context.Context, arg GetUserDataParams) (GetUserDataRow, error)
	GetUserDeviceID(ctx context.Context, arg GetUserDeviceIDParams) (string, error)
	GetUserIDByToken(ctx context.Context, token string) (string, error)
	GetUserStatus(ctx context.Context, email string) (string, error)
	InsertApp(ctx context.Context, arg InsertAppParams) error
	MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) error
	RegisterDevice(ctx context.Context, arg RegisterDeviceParams) error
	RegisterUser(ctx context.Context, arg RegisterUserParams) error
	UpdateLatestLoginAt(ctx context.Context, arg UpdateLatestLoginAtParams) error
}

var _ Querier = (*Queries)(nil)
