// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	DeleteApp(ctx context.Context, arg DeleteAppParams) error
	InsertApp(ctx context.Context, arg InsertAppParams) error
}

var _ Querier = (*Queries)(nil)
