name: Build and test

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: sso_dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Install golang-migrate
        run: |
          go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
          export PATH=$PATH:$(go env GOPATH)/bin
          which migrate

      - name: Install dependencies
        run: go mod download

      - name: Create .env file
        run: |
          set -x
          echo "${{ secrets.ENV_CONFIG_TEST }}" > ./config/.env

      - name: Wait for PostgreSQL to be ready
        run: sleep 10

      - name: Check PostgreSQL connection
        run: pg_isready -h localhost -p 5432

      - name: Run tests
        # TODO: maybe need to add env POSTGRESQL_URL here (?)
        run: make test-all-app

      - name: Notify results
        run: echo "Tests completed!"