name: Publish to Docker Hub

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number in "v1.2.3" format'
        required: true
  release:
    types: [published]

env:
  REGISTRY_IMAGE: rshelekhov/grpc-sso

jobs:
  build:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo into the Go module directory
        uses: actions/checkout@v3

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_RS_USER }}
          password: ${{ secrets.DOCKER_HUB_RS_PASSWORD }}

      - name: Build docker image and push to Docker Hub
        uses: docker/build-push-action@v4
        id: build
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY_IMAGE }}:${{ steps.version.outputs.version }}
            ${{ env.REGISTRY_IMAGE }}:latest
          push: true
